version: "3.3"

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "react"
    ports:
      - "3000:3000"

    networks:
      default_bridge:
        ipv4_address: 172.17.1.1

networks:
  default_bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.17.1.0/24