version: "3.3"

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "react"

    networks:
      default_bridge:
        ipv4_address: 172.25.1.3

networks:
  default_bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.25.1.0/24